// Copyright 2011 Software Freedom Conservatory
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


function(){return function(){var b="function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[d]=c.value)},h="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;
function k(a,d){if(d){for(var c=h,e=a.split("."),f=0;f<e.length-1;f++){var g=e[f];g in c||(c[g]={});c=c[g]}e=e[e.length-1];f=c[e];g=d(f);g!=f&&null!=g&&b(c,e,{configurable:!0,writable:!0,value:g})}}
k("String.prototype.repeat",function(a){return a?a:function(a){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var e="";a;)if(a&1&&(e+=c),a>>>=1)c+=c;return e}});k("Math.sign",function(a){return a?a:function(a){a=Number(a);return!a||isNaN(a)?a:0<a?1:-1}});var l=this;var m=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function n(a,d){for(var c=0,e=m(String(a)).split("."),f=m(String(d)).split("."),g=Math.max(e.length,f.length),w=0;!c&&w<g;w++){var Z=e[w]||"",aa=f[w]||"",ba=RegExp("(\\d*)(\\D*)","g"),ca=RegExp("(\\d*)(\\D*)","g");do{var p=ba.exec(Z)||["","",""],q=ca.exec(aa)||["","",""];if(0==p[0].length&&0==q[0].length)break;c=r(0==p[1].length?0:parseInt(p[1],10),0==q[1].length?0:parseInt(q[1],10))||r(0==p[2].length,0==q[2].length)||r(p[2],q[2])}while(!c)}return c}function r(a,d){return a<d?-1:a>d?1:0};var t;a:{var u=l.navigator;if(u){var v=u.userAgent;if(v){t=v;break a}}t=""}function x(a){return-1!=t.indexOf(a)};function y(){return x("Opera")||x("OPR")}function z(){return(x("Chrome")||x("CriOS"))&&!y()&&!x("Edge")};function A(){return x("iPhone")&&!x("iPod")&&!x("iPad")};var B=y(),C=x("Trident")||x("MSIE"),D=x("Edge"),E=x("Gecko")&&!(-1!=t.toLowerCase().indexOf("webkit")&&!x("Edge"))&&!(x("Trident")||x("MSIE"))&&!x("Edge"),da=-1!=t.toLowerCase().indexOf("webkit")&&!x("Edge");function ea(){var a=t;if(E)return/rv\:([^\);]+)(\)|;)/.exec(a);if(D)return/Edge\/([\d\.]+)/.exec(a);if(C)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(da)return/WebKit\/(\S+)/.exec(a)}function F(){var a=l.document;return a?a.documentMode:void 0}
var G=function(){if(B&&l.opera){var a;var d=l.opera.version;try{a=d()}catch(c){a=d}return a}a="";(d=ea())&&(a=d?d[1]:"");return C&&(d=F(),null!=d&&d>parseFloat(a))?String(d):a}(),H={};function I(a){H[a]||(H[a]=0<=n(G,a))}var J=l.document,K=J&&C?F()||("CSS1Compat"==J.compatMode?parseInt(G,10):5):void 0;var fa=x("Firefox"),ga=A()||x("iPod"),ha=x("iPad"),L=x("Android")&&!(z()||x("Firefox")||y()||x("Silk")),ia=z(),M=x("Safari")&&!(z()||x("Coast")||y()||x("Edge")||x("Silk")||x("Android"))&&!(A()||x("iPad")||x("iPod"));function N(a){return(a=a.exec(t))?a[1]:""}var ja=function(){if(fa)return N(/Firefox\/([0-9.]+)/);if(C||D||B)return G;if(ia)return N(/Chrome\/([0-9.]+)/);if(M&&!(A()||x("iPad")||x("iPod")))return N(/Version\/([0-9.]+)/);if(ga||ha){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(t);if(a)return a[1]+"."+a[2]}else if(L)return(a=N(/Android\s+([0-9.]+)/))?a:N(/Version\/([0-9.]+)/);return""}();var O,P;function Q(a){R?P(a):L?n(ka,a):n(ja,a)}var R=function(){if(!E)return!1;var a=l.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(g){return!1}var d=a.classes,a=a.interfaces,c=d["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),d=d["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),e=d.platformVersion,f=d.version;O=function(a){c.compare(e,""+a)};P=function(a){c.compare(f,""+a)};return!0}(),S;
if(L){var T=/Android\s+([0-9\.]+)/.exec(t);S=T?T[1]:"0"}else S="0";var ka=S,la=C&&!(9<=Number(K));L&&Q(2.3);L&&Q(4);M&&Q(6);!E&&!C||C&&9<=Number(K)||E&&I("1.9.1");C&&I("9");C&&(R?O(10):C?n(K,10):I(10));L&&Q(4);function U(a,d,c){c=d.a(a,c);"isTrusted"in c||(c.isTrusted=!1);return la&&a.fireEvent?a.fireEvent("on"+d.b,c):a.dispatchEvent(c)}var V=["_"],W=l;V[0]in W||!W.execScript||W.execScript("var "+V[0]);for(var X;V.length&&(X=V.shift());){var Y;if(Y=!V.length)Y=void 0!==U;Y?W[X]=U:W[X]?W=W[X]:W=W[X]={}};; return this._.apply(null,arguments);}.apply({navigator:typeof window!='undefined'?window.navigator:null,document:typeof window!='undefined'?window.document:null}, arguments);}
