// Copyright 2011 Software Freedom Conservatory
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

function(){return function(){var e="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},h="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;
function k(a,b){if(b){for(var c=h,d=a.split("."),f=0;f<d.length-1;f++){var g=d[f];g in c||(c[g]={});c=c[g]}d=d[d.length-1];f=c[d];g=b(f);g!=f&&null!=g&&e(c,d,{configurable:!0,writable:!0,value:g})}}
k("String.prototype.repeat",function(a){return a?a:function(a){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=c),a>>>=1)c+=c;return d}});k("Math.sign",function(a){return a?a:function(a){a=Number(a);return!a||isNaN(a)?a:0<a?1:-1}});var m=this;
function n(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}var r=Date.now||function(){return+new Date};function t(a,b){function c(){}c.prototype=b.prototype;a.g=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.f=function(a,c,g){for(var u=Array(arguments.length-2),l=2;l<arguments.length;l++)u[l-2]=arguments[l];return b.prototype[c].apply(a,u)}};function v(a){if(Error.captureStackTrace)Error.captureStackTrace(this,v);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}t(v,Error);v.prototype.name="CustomError";function w(a,b){for(var c=a.split("%s"),d="",f=Array.prototype.slice.call(arguments,1);f.length&&1<c.length;)d+=c.shift()+f.shift();return d+c.join("%s")}var x=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function y(a,b){return a<b?-1:a>b?1:0};function z(a,b){b.unshift(a);v.call(this,w.apply(null,b));b.shift()}t(z,v);z.prototype.name="AssertionError";function A(a,b){throw new z("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var B;a:{var C=m.navigator;if(C){var D=C.userAgent;if(D){B=D;break a}}B=""};var E=-1!=B.indexOf("Opera")||-1!=B.indexOf("OPR"),F=-1!=B.indexOf("Trident")||-1!=B.indexOf("MSIE"),aa=-1!=B.indexOf("Edge"),G=-1!=B.indexOf("Gecko")&&!(-1!=B.toLowerCase().indexOf("webkit")&&-1==B.indexOf("Edge"))&&!(-1!=B.indexOf("Trident")||-1!=B.indexOf("MSIE"))&&-1==B.indexOf("Edge"),ba=-1!=B.toLowerCase().indexOf("webkit")&&-1==B.indexOf("Edge");
function ca(){var a=B;if(G)return/rv\:([^\);]+)(\)|;)/.exec(a);if(aa)return/Edge\/([\d\.]+)/.exec(a);if(F)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(ba)return/WebKit\/(\S+)/.exec(a)}function H(){var a=m.document;return a?a.documentMode:void 0}var I=function(){if(E&&m.opera){var a;var b=m.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=ca())&&(a=b?b[1]:"");return F&&(b=H(),null!=b&&b>parseFloat(a))?String(b):a}(),J={};
function K(a){if(!J[a]){for(var b=0,c=x(String(I)).split("."),d=x(String(a)).split("."),f=Math.max(c.length,d.length),g=0;!b&&g<f;g++){var u=c[g]||"",l=d[g]||"",da=RegExp("(\\d*)(\\D*)","g"),ea=RegExp("(\\d*)(\\D*)","g");do{var p=da.exec(u)||["","",""],q=ea.exec(l)||["","",""];if(0==p[0].length&&0==q[0].length)break;b=y(0==p[1].length?0:parseInt(p[1],10),0==q[1].length?0:parseInt(q[1],10))||y(0==p[2].length,0==q[2].length)||y(p[2],q[2])}while(!b)}J[a]=0<=b}}
var L=m.document,fa=L&&F?H()||("CSS1Compat"==L.compatMode?parseInt(I,10):5):void 0;var M;if(!(M=!G&&!F)){var N;if(N=F)N=9<=Number(fa);M=N}M||G&&K("1.9.1");F&&K("9");function O(a,b,c,d,f){"number"==typeof f||ga++;d||r();this.b=b;delete this.a}O.prototype.a=null;var ga=0;function P(){this.b=this.c=this.a=null}function Q(a,b){this.name=a;this.value=b}Q.prototype.toString=function(){return this.name};var ha=new Q("CONFIG",700);function R(a){if(a.c)return a.c;if(a.a)return R(a.a);A("Root logger has no level set.");return null}
P.prototype.log=function(a,b,c){if(a.value>=R(this).value)for("function"==n(b)&&(b=b()),a=new O(0,String(b)),c&&(a.a=c),c="log:"+a.b,m.console&&(m.console.timeStamp?m.console.timeStamp(c):m.console.markTimeline&&m.console.markTimeline(c)),m.msWriteProfilerMark&&m.msWriteProfilerMark(c),c=this;c;)c=c.a};var S={},T=null;function U(a){T||(T=new P,S[""]=T,T.c=ha);var b;if(!(b=S[a])){b=new P;var c=a.lastIndexOf("."),d=a.substr(c+1),c=U(a.substr(0,c));c.b||(c.b={});c.b[d]=b;b.a=c;S[a]=b}return b};U("goog.dom.SavedRange");U("goog.dom.browserrange.IeRange");function V(){var a="";window.getSelection?a=window.getSelection().toString():document.selection&&"Control"!=document.selection.type&&(a=document.selection.createRange().text);return a}var W=["_"],X=m;W[0]in X||!X.execScript||X.execScript("var "+W[0]);for(var Y;W.length&&(Y=W.shift());){var Z;if(Z=!W.length)Z=void 0!==V;Z?X[Y]=V:X[Y]?X=X[Y]:X=X[Y]={}};; return this._.apply(null,arguments);}.apply({navigator:typeof window!='undefined'?window.navigator:null,document:typeof window!='undefined'?window.document:null}, arguments);}
