// Copyright 2011 Software Freedom Conservatory
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

function(){return function(){var h,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;
function ca(a,b){if(b){for(var c=ba,d=a.split("."),e=0;e<d.length-1;e++){var f=d[e];f in c||(c[f]={});c=c[f]}d=d[d.length-1];e=c[d];f=b(e);f!=e&&null!=f&&aa(c,d,{configurable:!0,writable:!0,value:f})}}
ca("String.prototype.repeat",function(a){return a?a:function(a){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=c),a>>>=1)c+=c;return d}});ca("Math.sign",function(a){return a?a:function(a){a=Number(a);return!a||isNaN(a)?a:0<a?1:-1}});var l=this;
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function n(a){var b=da(a);return"array"==b||"object"==b&&"number"==typeof a.length}function q(a){return"string"==typeof a}function ea(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var fa=Date.now||function(){return+new Date};
function r(a,b){function c(){}c.prototype=b.prototype;a.F=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.O=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}};function u(a){if(Error.captureStackTrace)Error.captureStackTrace(this,u);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}r(u,Error);u.prototype.name="CustomError";function ga(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")}var ha=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function v(a,b){return a<b?-1:a>b?1:0};function w(a,b){b.unshift(a);u.call(this,ga.apply(null,b));b.shift()}r(w,u);w.prototype.name="AssertionError";function ia(a,b){throw new w("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};function x(a,b){if(q(a))return q(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function ja(a,b){var c;a:{c=a.length;for(var d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:q(a)?a.charAt(c):a[c]}function ka(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var y;a:{var la=l.navigator;if(la){var ma=la.userAgent;if(ma){y=ma;break a}}y=""};var na=-1!=y.indexOf("Opera")||-1!=y.indexOf("OPR"),z=-1!=y.indexOf("Trident")||-1!=y.indexOf("MSIE"),oa=-1!=y.indexOf("Edge"),A=-1!=y.indexOf("Gecko")&&!(-1!=y.toLowerCase().indexOf("webkit")&&-1==y.indexOf("Edge"))&&!(-1!=y.indexOf("Trident")||-1!=y.indexOf("MSIE"))&&-1==y.indexOf("Edge"),pa=-1!=y.toLowerCase().indexOf("webkit")&&-1==y.indexOf("Edge");
function qa(){var a=y;if(A)return/rv\:([^\);]+)(\)|;)/.exec(a);if(oa)return/Edge\/([\d\.]+)/.exec(a);if(z)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(pa)return/WebKit\/(\S+)/.exec(a)}function ra(){var a=l.document;return a?a.documentMode:void 0}var sa=function(){if(na&&l.opera){var a;var b=l.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=qa())&&(a=b?b[1]:"");return z&&(b=ra(),null!=b&&b>parseFloat(a))?String(b):a}(),ta={};
function ua(a){var b;if(!(b=ta[a])){b=0;for(var c=ha(String(sa)).split("."),d=ha(String(a)).split("."),e=Math.max(c.length,d.length),f=0;!b&&f<e;f++){var g=c[f]||"",k=d[f]||"",m=RegExp("(\\d*)(\\D*)","g"),t=RegExp("(\\d*)(\\D*)","g");do{var p=m.exec(g)||["","",""],F=t.exec(k)||["","",""];if(0==p[0].length&&0==F[0].length)break;b=v(0==p[1].length?0:parseInt(p[1],10),0==F[1].length?0:parseInt(F[1],10))||v(0==p[2].length,0==F[2].length)||v(p[2],F[2])}while(!b)}b=ta[a]=0<=b}return b}
var va=l.document,B=va&&z?ra()||("CSS1Compat"==va.compatMode?parseInt(sa,10):5):void 0;!A&&!z||z&&9<=Number(B)||A&&ua("1.9.1");z&&ua("9");function wa(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0}
function C(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function xa(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(z&&!(9<=Number(B))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?ya(a,b):!c&&C(e,b)?-1*za(a,b):!d&&C(f,a)?za(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=D(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);d=d.createRange();d.selectNode(b);d.collapse(!0);return c.compareBoundaryPoints(l.Range.START_TO_END,d)}function za(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return ya(d,a)}function ya(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1}function D(a){return 9==a.nodeType?a:a.ownerDocument||a.document};var E="StopIteration"in l?l.StopIteration:{message:"StopIteration",stack:""};function G(){}G.prototype.s=function(){throw E;};G.prototype.B=function(){return this};function Aa(a){if(a instanceof G)return a;if("function"==typeof a.B)return a.B(!1);if(n(a)){var b=0,c=new G;c.s=function(){for(;;){if(b>=a.length)throw E;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");}
function Ba(a,b){if(n(a))try{for(var c=a,d=c.length,e=q(c)?c.split(""):c,f=0;f<d;f++)f in e&&b.call(void 0,e[f],f,c)}catch(g){if(g!==E)throw g;}else{a=Aa(a);try{for(;;)b.call(void 0,a.s(),void 0,a)}catch(g){if(g!==E)throw g;}}}function Ca(a){if(n(a))return ka(a);a=Aa(a);var b=[];Ba(a,function(a){b.push(a)});return b};function Da(a,b,c,d,e){"number"==typeof e||Ea++;d||fa();this.b=b;delete this.a}Da.prototype.a=null;var Ea=0;function Fa(){this.b=this.f=this.a=null}function Ga(a,b){this.name=a;this.value=b}Ga.prototype.toString=function(){return this.name};var Ha=new Ga("SEVERE",1E3),Ia=new Ga("CONFIG",700);function Ja(a){if(a.f)return a.f;if(a.a)return Ja(a.a);ia("Root logger has no level set.");return null}
Fa.prototype.log=function(a,b,c){if(a.value>=Ja(this).value)for("function"==da(b)&&(b=b()),a=new Da(0,String(b)),c&&(a.a=c),c="log:"+a.b,l.console&&(l.console.timeStamp?l.console.timeStamp(c):l.console.markTimeline&&l.console.markTimeline(c)),l.msWriteProfilerMark&&l.msWriteProfilerMark(c),c=this;c;)c=c.a};var Ka={},H=null;
function La(a){H||(H=new Fa,Ka[""]=H,H.f=Ia);var b;if(!(b=Ka[a])){b=new Fa;var c=a.lastIndexOf("."),d=a.substr(c+1),c=La(a.substr(0,c));c.b||(c.b={});c.b[d]=b;b.a=c;Ka[a]=b}return b};function Ma(a){var b=Na;b&&b.log(Ha,a,void 0)};La("goog.dom.SavedRange");function I(a,b,c,d,e){this.a=!!b;this.node=null;this.c=0;this.H=!1;this.D=!c;a&&J(this,a,d);this.g=void 0!=e?e:this.c||0;this.a&&(this.g*=-1)}r(I,G);function J(a,b,c){if(a.node=b)a.c="number"==typeof c?c:1!=a.node.nodeType?0:a.a?-1:1}I.prototype.G=function(a){this.node=a.node;this.c=a.c;this.g=a.g;this.a=a.a;this.D=a.D};I.prototype.clone=function(){return new I(this.node,this.a,!this.D,this.c,this.g)};
I.prototype.s=function(){var a;if(this.H){if(!this.node||this.D&&!this.g)throw E;a=this.node;var b=this.a?-1:1;if(this.c==b){var c=this.a?a.lastChild:a.firstChild;c?J(this,c):J(this,a,-1*b)}else(c=this.a?a.previousSibling:a.nextSibling)?J(this,c):J(this,a.parentNode,-1*b);this.g+=this.c*(this.a?-1:1)}else this.H=!0;a=this.node;if(!this.node)throw E;return a};
I.prototype.splice=function(a){var b=this.node,c=this.a?1:-1;this.c==c&&(this.c=-1*c,this.g+=this.c*(this.a?-1:1));this.a=!this.a;I.prototype.s.call(this);this.a=!this.a;for(var c=n(arguments[0])?arguments[0]:arguments,d=c.length-1;0<=d;d--)b.parentNode&&b.parentNode.insertBefore(c[d],b.nextSibling);b&&b.parentNode&&b.parentNode.removeChild(b)};function Oa(){}function Pa(a,b){I.call(this,a,b,!0)}r(Pa,I);function K(a,b,c,d,e){this.b=this.f=null;this.v=this.w=0;var f;a&&(this.f=a,this.w=b,this.b=c,this.v=d,1==a.nodeType&&"BR"!=a.tagName&&(a=a.childNodes,(b=a[b])?(this.f=b,this.w=0):(a.length&&(this.f=a[a.length-1]),f=!0)),1==c.nodeType&&((this.b=c.childNodes[d])?this.v=0:this.b=c));I.call(this,e?this.b:this.f,e,!0);if(f)try{this.s()}catch(g){if(g!=E)throw g;}}r(K,Pa);K.prototype.N=function(){return this.H&&this.node==this.b&&(!this.v||1!=this.c)};K.prototype.s=function(){if(this.N())throw E;return K.F.s.call(this)};
K.prototype.G=function(a){this.f=a.f;this.b=a.b;this.w=a.w;this.v=a.v;this.h=a.h;K.F.G.call(this,a)};K.prototype.clone=function(){var a=new K(this.f,this.w,this.b,this.v,this.h);a.G(this);return a};function Qa(){}function Ra(a,b){var c=b.C();try{return 0<=a.j(c,0,0)&&0>=a.j(c,1,1)}catch(d){if(!z)throw d;return!1}}Qa.prototype.B=function(){return new K(this.i(),this.o(),this.m(),this.u())};function L(a){this.a=a}r(L,Qa);function M(a){var b=D(a).createRange();if(3==a.nodeType)b.setStart(a,0),b.setEnd(a,a.length);else if(N(a)){for(var c,d=a;(c=d.firstChild)&&N(c);)d=c;b.setStart(d,0);for(d=a;(c=d.lastChild)&&N(c);)d=c;b.setEnd(d,1==d.nodeType?d.childNodes.length:d.length)}else c=a.parentNode,a=x(c.childNodes,a),b.setStart(c,a),b.setEnd(c,a+1);return b}function O(a,b,c,d){var e=D(a).createRange();e.setStart(a,b);e.setEnd(c,d);return e}h=L.prototype;h.clone=function(){return new this.constructor(this.a.cloneRange())};
h.C=function(){return this.a};h.M=function(){return this.a.commonAncestorContainer};h.i=function(){return this.a.startContainer};h.o=function(){return this.a.startOffset};h.m=function(){return this.a.endContainer};h.u=function(){return this.a.endOffset};h.j=function(a,b,c){return this.a.compareBoundaryPoints(1==c?1==b?l.Range.START_TO_START:l.Range.START_TO_END:1==b?l.Range.END_TO_START:l.Range.END_TO_END,a)};h.l=function(){return this.a.collapsed};
h.select=function(a){var b=D(this.i());this.A((b?b.parentWindow||b.defaultView:window).getSelection(),a)};h.A=function(a){a.removeAllRanges();a.addRange(this.a)};function P(a){this.a=a}r(P,L);P.prototype.A=function(a,b){!b||this.l()?P.F.A.call(this,a,b):(a.collapse(this.m(),this.u()),a.extend(this.i(),this.o()))};function Q(a,b){this.b=this.f=this.h=null;this.g=this.c=-1;this.a=a;this.s=b}r(Q,Qa);var Na=La("goog.dom.browserrange.IeRange");
function R(a){var b=D(a).body.createTextRange();if(1==a.nodeType)b.moveToElementText(a),N(a)&&!a.childNodes.length&&b.collapse(!1);else{for(var c=0,d=a;d=d.previousSibling;){var e=d.nodeType;if(3==e)c+=d.length;else if(1==e){b.moveToElementText(d);break}}d||b.moveToElementText(a.parentNode);b.collapse(!d);c&&b.move("character",c);b.moveEnd("character",a.length)}return b}h=Q.prototype;h.clone=function(){var a=new Q(this.a.duplicate(),this.s);a.h=this.h;a.f=this.f;a.b=this.b;return a};h.C=function(){return this.a};
h.M=function(){if(!this.h){var a=this.a.text,b=this.a.duplicate(),c=a.replace(/ +$/,"");(c=a.length-c.length)&&b.moveEnd("character",-c);c=b.parentElement();b=b.htmlText.replace(/(\r\n|\r|\n)+/g," ").length;if(this.l()&&0<b)return this.h=c;for(;b>c.outerHTML.replace(/(\r\n|\r|\n)+/g," ").length;)c=c.parentNode;for(;1==c.childNodes.length&&c.innerText==Sa(c.firstChild)&&N(c.firstChild);)c=c.firstChild;0==a.length&&(c=Ta(this,c));this.h=c}return this.h};
function Ta(a,b){for(var c=b.childNodes,d=0,e=c.length;d<e;d++){var f=c[d];if(N(f)){var g=R(f),k=g.htmlText!=f.outerHTML;if(a.l()&&k?0<=a.j(g,1,1)&&0>=a.j(g,1,0):a.a.inRange(g))return Ta(a,f)}}return b}h.i=function(){this.f||(this.f=S(this,1),this.l()&&(this.b=this.f));return this.f};h.o=function(){0>this.c&&(this.c=Ua(this,1),this.l()&&(this.g=this.c));return this.c};h.m=function(){if(this.l())return this.i();this.b||(this.b=S(this,0));return this.b};
h.u=function(){if(this.l())return this.o();0>this.g&&(this.g=Ua(this,0),this.l()&&(this.c=this.g));return this.g};h.j=function(a,b,c){return this.a.compareEndPoints((1==b?"Start":"End")+"To"+(1==c?"Start":"End"),a)};
function S(a,b,c){c=c||a.M();if(!c||!c.firstChild)return c;for(var d=1==b,e=0,f=c.childNodes.length;e<f;e++){var g=d?e:f-e-1,k=c.childNodes[g],m;try{m=Va(k)}catch(p){continue}var t=m.C();if(a.l())if(!N(k)){if(!a.j(t,1,1)){a.c=a.g=g;break}}else{if(Ra(m,a))return S(a,b,k)}else{if(Ra(a,m)){if(!N(k)){d?a.c=g:a.g=g+1;break}return S(a,b,k)}if(0>a.j(t,1,0)&&0<a.j(t,0,1))return S(a,b,k)}}return c}
function Ua(a,b){var c=1==b,d=c?a.i():a.m();if(1==d.nodeType){for(var d=d.childNodes,e=d.length,f=c?1:-1,g=c?0:e-1;0<=g&&g<e;g+=f){var k=d[g];if(!N(k)&&!a.a.compareEndPoints((1==b?"Start":"End")+"To"+(1==b?"Start":"End"),Va(k).C()))return c?g:g+1}return-1==g?0:g}e=a.a.duplicate();f=R(d);e.setEndPoint(c?"EndToEnd":"StartToStart",f);e=e.text.length;return c?d.length-e:e}function Sa(a){return 3==a.nodeType?a.nodeValue:a.innerText}h.l=function(){return 0==this.a.compareEndPoints("StartToEnd",this.a)};
h.select=function(){this.a.select()};function T(a){this.a=a}r(T,L);T.prototype.A=function(a){a.collapse(this.i(),this.o());this.m()==this.i()&&this.u()==this.o()||a.extend(this.m(),this.u());a.rangeCount||a.addRange(this.a)};function U(a){this.a=a}r(U,L);U.prototype.j=function(a,b,c){return ua("528")?U.F.j.call(this,a,b,c):this.a.compareBoundaryPoints(1==c?1==b?l.Range.START_TO_START:l.Range.END_TO_START:1==b?l.Range.START_TO_END:l.Range.END_TO_END,a)};U.prototype.A=function(a,b){b?a.setBaseAndExtent(this.m(),this.u(),this.i(),this.o()):a.setBaseAndExtent(this.i(),this.o(),this.m(),this.u())};function Va(a){if(!z||9<=Number(B))a=pa?new U(M(a)):A?new P(M(a)):na?new T(M(a)):new L(M(a));else{var b=new Q(R(a),D(a));if(N(a)){for(var c,d=a;(c=d.firstChild)&&N(c);)d=c;b.f=d;b.c=0;for(d=a;(c=d.lastChild)&&N(c);)d=c;b.b=d;b.g=1==d.nodeType?d.childNodes.length:d.length;b.h=a}else b.f=b.b=b.h=a.parentNode,b.c=x(b.h.childNodes,a),b.g=b.c+1;a=b}return a}function N(a){return wa(a)||3==a.nodeType};function V(){this.a=this.b=this.c=this.f=this.g=null;this.h=!1}r(V,Oa);function Wa(a){var b=new V;b.g=a;b.h=!1;return b}function Xa(a,b,c,d){var e=new V;e.h=Ya(a,b,c,d);if(ea(a)&&1==a.nodeType&&!wa(a)){var f=a.parentNode;b=x(f.childNodes,a);a=f}ea(c)&&1==c.nodeType&&!wa(c)&&(f=c.parentNode,d=x(f.childNodes,c),c=f);e.h?(e.f=c,e.c=d,e.b=a,e.a=b):(e.f=a,e.c=b,e.b=c,e.a=d);return e}h=V.prototype;
h.clone=function(){var a=new V;a.g=this.g&&this.g.clone();a.f=this.f;a.c=this.c;a.b=this.b;a.a=this.a;a.h=this.h;return a};
function W(a){var b;if(!(b=a.g)){b=a.K();var c=a.L(),d=a.I(),e=a.J();if(!z||9<=Number(B))b=pa?new U(O(b,c,d,e)):A?new P(O(b,c,d,e)):na?new T(O(b,c,d,e)):new L(O(b,c,d,e));else{var f=b,g=c,k=d,m=e,t=!1;1==f.nodeType&&(g>f.childNodes.length&&Ma("Cannot have startOffset > startNode child count"),g=f.childNodes[g],t=!g,f=g||f.lastChild||f,g=0);var p=R(f);g&&p.move("character",g);f==k&&g==m?p.collapse(!0):(t&&p.collapse(!1),t=!1,1==k.nodeType&&(m>k.childNodes.length&&Ma("Cannot have endOffset > endNode child count"),
k=(g=k.childNodes[m])||k.lastChild||k,m=0,t=!g),f=R(k),f.collapse(!t),m&&f.moveEnd("character",m),p.setEndPoint("EndToEnd",f));m=new Q(p,D(b));m.f=b;m.c=c;m.b=d;m.g=e;b=m}b=a.g=b}return b}h.K=function(){return this.f||(this.f=W(this).i())};h.L=function(){return null!=this.c?this.c:this.c=W(this).o()};h.I=function(){return this.b||(this.b=W(this).m())};h.J=function(){return null!=this.a?this.a:this.a=W(this).u()};h.B=function(){return new K(this.K(),this.L(),this.I(),this.J())};h.select=function(){W(this).select(this.h)};function Ya(a,b,c,d){if(a==c)return d<b;var e;if(1==a.nodeType&&b)if(e=a.childNodes[b])a=e,b=0;else if(C(a,c))return!0;if(1==c.nodeType&&d)if(e=c.childNodes[d])c=e,d=0;else if(C(c,a))return!1;return 0<(xa(a,c)||b-d)};function Za(a,b){var c=Wa(Va(a)),c=ja(Ca(c),function(a){return 3==a.nodeType&&-1!=a.data.indexOf(b)});if(!c)throw"could not find text node matching: "+b;var d=c.data.indexOf(b);Xa(c,d,c,d+b.length).select()}var X=["_"],Y=l;X[0]in Y||!Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());){var $a;if($a=!X.length)$a=void 0!==Za;$a?Y[Z]=Za:Y[Z]?Y=Y[Z]:Y=Y[Z]={}};; return this._.apply(null,arguments);}.apply({navigator:typeof window!='undefined'?window.navigator:null,document:typeof window!='undefined'?window.document:null}, arguments);}
