// the-thead-element
[TagName=thead]
interface HTMLTheadElement : HTMLTableSectionElement {};

// the-dd-element
[TagName=dd]
interface HTMLDdElement : HTMLElement {};

// the-address-element
[TagName=address]
interface HTMLAddressElement : HTMLElement {};

// the-nav-element
[TagName=nav]
interface HTMLNavElement : HTMLElement {};

// the-tfoot-element
[TagName=tfoot]
interface HTMLTFootElement : HTMLTableSectionElement {};

// the-sub-and-sup-elements
[TagName=sub]
interface HTMLSubElement : HTMLElement {};
[TagName=sup]
interface HTMLSupElement : HTMLElement {};

// the-bdo-element
[TagName=bdo]
interface HTMLBdoElement : HTMLElement {};

// the-rp-element
[TagName=rp]
interface HTMLRpElement : HTMLElement {};

// the-rt-element
[TagName=rt]
interface HTMLRtElement : HTMLElement {};

// the-mark-element
[TagName=mark]
interface HTMLMarkElement : HTMLElement {};

// the-kbd-element
[TagName=kbd]
interface HTMLKbdElement : HTMLElement {};

// the-dfn-element
[TagName=dfn]
interface HTMLDfnElement : HTMLElement {};

// the-cite-element
[TagName=cite]
interface HTMLCiteElement : HTMLElement {};

// the-ins-element
[TagName=ins]
interface HTMLInsElement : HTMLModElement {};

// the-b-element
[TagName=b]
interface HTMLBElement : HTMLElement {};

// the-noscript-element
[TagName=noscript]
interface HTMLNoscriptElement : HTMLElement {};

// the-figure-element
[TagName=figure]
interface HTMLFigureElement : HTMLElement {};

// the-code-element
[TagName=code]
interface HTMLCodeElement : HTMLElement {};

// the-q-element
[TagName=q]
interface HTMLQElement : HTMLQuoteElement {};

// the-strong-element
[TagName=strong]
interface HTMLStrongElement : HTMLElement {};

// the-header-element
[TagName=header]
interface HTMLHeaderElement : HTMLElement {};

// the-hgroup-element
[TagName=hgroup]
interface HTMLHgroupElement : HTMLElement {};

// the-aside-element
[TagName=aside]
interface HTMLAsideElement : HTMLElement {};

// the-samp-element
[TagName=samp]
interface HTMLSampElement : HTMLElement {};

// the-section-element
[TagName=section]
interface HTMLSectionElement : HTMLElement {};

// the-dt-element
[TagName=dt]
interface HTMLDtElement : HTMLElement {};

// the-col-element
[TagName=col]
interface HTMLColElement : HTMLTableColElement {};

// the-i-element
[TagName=i]
interface HTMLIElement : HTMLElement {};

// the-var-element
[TagName=var]
interface HTMLVarElement : HTMLElement {};

// the-abbr-element
[TagName=abbr]
interface HTMLAbbrElement : HTMLElement {};

// the-small-element
[TagName=small]
interface HTMLSmallElement : HTMLElement {};

// the-footer-element
[TagName=footer]
interface HTMLFooterElement : HTMLElement {};

// the-ruby-element
[TagName=ruby]
interface HTMLRubyElement : HTMLElement {};

// the-article-element
[TagName=article]
interface HTMLArticleElement : HTMLElement {};

// the-del-element
[TagName=del]
interface HTMLDelElement : HTMLModElement {};

// the-em-element
[TagName=em]
interface HTMLEmElement : HTMLElement {};
