# Autogenerated from the HTML5 specification. Edits may be lost.
module Watir














  class HTMLElement < Element
    attributes(:string => ([:innerhtml, :outerhtml, :id, :title, :lang, :dir, :class_name, :item_type, :item_id, :item_value, :access_key, :access_key_label, :content_editable, :spellcheck, :command_type, :label, :icon]), :token_list => ([:class_list, :item_ref, :item_prop]), :string_map => ([:dataset]), :bool => ([:item_scope, :hidden, :draggable, :is_content_editable, :disabled, :checked]), :properties_collection => ([:properties]), :int => ([:tab_index]), :html_element => ([:context_menu]), :style => ([:style]), :function => ([:onabort, :onblur, :oncanplay, :oncanplaythrough, :onchange, :onclick, :oncontextmenu, :oncuechange, :ondblclick, :ondrag, :ondragend, :ondragenter, :ondragleave, :ondragover, :ondragstart, :ondrop, :ondurationchange, :onemptied, :onended, :onerror, :onfocus, :onformchange, :onforminput, :oninput, :oninvalid, :onkeydown, :onkeypress, :onkeyup, :onload, :onloadeddata, :onloadedmetadata, :onloadstart, :onmousedown, :onmousemove, :onmouseout, :onmouseover, :onmouseup, :onmousewheel, :onpause, :onplay, :onplaying, :onprogress, :onratechange, :onreadystatechange, :onscroll, :onseeked, :onseeking, :onselect, :onshow, :onstalled, :onsubmit, :onsuspend, :ontimeupdate, :onvolumechange, :onwaiting]))
  end
  class Unknown < HTMLElement
    # do nothing
  end
  class Html < HTMLElement
    # do nothing
  end
  class Html < HTMLElement
    attributes(:string => ([:version]))
  end
  class Head < HTMLElement
    # do nothing
  end
  class Title < HTMLElement
    attributes(:string => ([:text]))
  end
  class Base < HTMLElement
    attributes(:string => ([:href, :target]))
  end
  class Meta < HTMLElement
    attributes(:string => ([:name, :http_equiv, :content]))
  end
  class Meta < HTMLElement
    attributes(:string => ([:scheme]))
  end
  class Style < HTMLElement
    attributes(:bool => ([:disabled, :scoped]), :string => ([:media, :type]))
  end
  class Script < HTMLElement
    attributes(:string => ([:src, :type, :charset, :text]), :bool => ([:async, :defer]))
  end
  class Script < HTMLElement
    attributes(:string => ([:event, :html_for]))
  end
  class Body < HTMLElement
    attributes(:function => ([:onafterprint, :onbeforeprint, :onbeforeunload, :onblur, :onerror, :onfocus, :onhashchange, :onload, :onmessage, :onoffline, :ononline, :onpopstate, :onpagehide, :onpageshow, :onredo, :onresize, :onstorage, :onundo, :onunload]))
  end
  class Body < HTMLElement
    attributes(:string => ([:text, :bg_color, :background, :link, :v_link, :a_link]))
  end
  class Heading < HTMLElement
    # do nothing
  end
  class Heading < HTMLElement
    attributes(:string => ([:align]))
  end
  class Paragraph < HTMLElement
    # do nothing
  end
  class Paragraph < HTMLElement
    attributes(:string => ([:align]))
  end
  class HR < HTMLElement
    # do nothing
  end
  class HR < HTMLElement
    attributes(:string => ([:align, :color, :size, :width]), :bool => ([:no_shade]))
  end
  class Pre < HTMLElement
    # do nothing
  end
  class Pre < HTMLElement
    attributes(:int => ([:width]))
  end
  class Quote < HTMLElement
    attributes(:string => ([:cite]))
  end
  class OList < HTMLElement
    attributes(:bool => ([:reversed]), :int => ([:start]))
  end
  class OList < HTMLElement
    attributes(:bool => ([:compact]), :string => ([:type]))
  end
  class UList < HTMLElement
    # do nothing
  end
  class UList < HTMLElement
    attributes(:bool => ([:compact]), :string => ([:type]))
  end
  class LI < HTMLElement
    attributes(:int => ([:value]))
  end
  class LI < HTMLElement
    attributes(:string => ([:type]))
  end
  class DList < HTMLElement
    # do nothing
  end
  class DList < HTMLElement
    attributes(:bool => ([:compact]))
  end
  class Div < HTMLElement
    # do nothing
  end
  class Div < HTMLElement
    attributes(:string => ([:align]))
  end
  class Anchor < HTMLElement
    attributes(:string => ([:href, :target, :ping, :rel, :media, :hreflang, :type, :text, :protocol, :host, :hostname, :port, :pathname, :search, :hash]), :token_list => ([:rel_list]))
  end
  class Anchor < HTMLElement
    attributes(:string => ([:coords, :charset, :name, :rev, :shape]))
  end
  class Time < HTMLElement
    attributes(:string => ([:date_time]), :bool => ([:pub_date]), :date => ([:value_as_date]))
  end
  class Span < HTMLElement
    # do nothing
  end
  class BR < HTMLElement
    # do nothing
  end
  class BR < HTMLElement
    attributes(:string => ([:clear]))
  end
  class Mod < HTMLElement
    attributes(:string => ([:cite, :date_time]))
  end
  class Image < HTMLElement
    attributes(:string => ([:alt, :src, :use_map]), :bool => ([:is_map, :complete]), :int => ([:width, :height, :natural_width, :natural_height]))
  end
  class Image < HTMLElement
    attributes(:string => ([:name, :align, :border, :long_desc]), :int => ([:hspace, :vspace]))
  end
  class IFrame < HTMLElement
    attributes(:string => ([:src, :srcdoc, :name, :width, :height, :content_window]), :token_list => ([:sandbox]), :bool => ([:seamless]), :document => ([:content_document]))
  end
  class IFrame < HTMLElement
    attributes(:string => ([:align, :frame_border, :long_desc, :margin_height, :margin_width, :scrolling]))
  end
  class Embed < HTMLElement
    attributes(:string => ([:src, :type, :width, :height]))
  end
  class Embed < HTMLElement
    attributes(:string => ([:align, :name]))
  end
  class Object < HTMLElement
    attributes(:string => ([:data, :type, :name, :use_map, :width, :height, :content_window, :validity, :validation_message]), :html_element => ([:form]), :document => ([:content_document]), :bool => ([:will_validate]))
  end
  class Object < HTMLElement
    attributes(:string => ([:align, :archive, :border, :code, :code_base, :code_type, :standby]), :bool => ([:declare]), :int => ([:hspace, :vspace]))
  end
  class Param < HTMLElement
    attributes(:string => ([:name, :value]))
  end
  class Param < HTMLElement
    attributes(:string => ([:type, :value_type]))
  end
  class Media < HTMLElement
    attributes(:string => ([:error, :src, :current_src, :preload, :buffered, :played, :seekable, :tracks]), :int => ([:network_state, :ready_state]), :bool => ([:seeking, :paused, :ended, :autoplay, :loop, :controls, :muted]), :float => ([:current_time, :start_time, :duration, :default_playback_rate, :playback_rate, :volume]))
  end
  class Video < Media
    attributes(:string => ([:width, :height, :poster]), :int => ([:video_width, :video_height]))
  end
  class Audio < Media
    # do nothing
  end
  class Source < HTMLElement
    attributes(:string => ([:src, :type, :media]))
  end
  class Track < HTMLElement
    attributes(:string => ([:kind, :label, :src, :srclang, :track]))
  end






  class Canvas < HTMLElement
    attributes(:int => ([:width, :height]))
  end






  class Map < HTMLElement
    attributes(:string => ([:name]), :html_collection => ([:areas, :images]))
  end
  class Area < HTMLElement
    attributes(:string => ([:alt, :coords, :shape, :href, :target, :ping, :rel, :media, :hreflang, :type, :protocol, :host, :hostname, :port, :pathname, :search, :hash]), :token_list => ([:rel_list]))
  end
  class Area < HTMLElement
    attributes(:bool => ([:no_href]))
  end
  class Table < HTMLElement
    attributes(:html_element => ([:caption, :t_head, :t_foot]), :html_collection => ([:t_bodies, :rows]), :string => ([:summary]))
  end
  class Table < HTMLElement
    attributes(:string => ([:align, :bg_color, :border, :cell_padding, :cell_spacing, :frame, :rules, :width]))
  end
  class TableCaption < HTMLElement
    # do nothing
  end
  class TableCaption < HTMLElement
    attributes(:string => ([:align]))
  end
  class TableCol < HTMLElement
    attributes(:int => ([:span]))
  end
  class TableCol < HTMLElement
    attributes(:string => ([:align, :ch, :ch_off, :v_align, :width]))
  end
  class TableSection < HTMLElement
    attributes(:html_collection => ([:rows]))
  end
  class TableSection < HTMLElement
    attributes(:string => ([:align, :ch, :ch_off, :v_align]))
  end
  class TableRow < HTMLElement
    attributes(:int => ([:row_index, :section_row_index]), :html_collection => ([:cells]))
  end
  class TableRow < HTMLElement
    attributes(:string => ([:align, :bg_color, :ch, :ch_off, :v_align]))
  end
  class TableCell < HTMLElement
    attributes(:int => ([:col_span, :row_span, :cell_index]), :token_list => ([:headers]))
  end
  class TableCell < HTMLElement
    attributes(:string => ([:abbr, :align, :axis, :bg_color, :ch, :ch_off, :height, :v_align, :width]), :bool => ([:no_wrap]))
  end
  class TableDataCell < TableCell
    # do nothing
  end
  class TableHeaderCell < TableCell
    attributes(:string => ([:scope]))
  end
  class Form < HTMLElement
    attributes(:string => ([:accept_charset, :action, :autocomplete, :enctype, :method, :name, :target]), :bool => ([:no_validate]), :html_collection => ([:elements]), :int => ([:length]))
  end
  class FieldSet < HTMLElement
    attributes(:bool => ([:disabled, :will_validate]), :html_element => ([:form]), :string => ([:name, :type, :validity, :validation_message]), :html_collection => ([:elements]))
  end
  class Legend < HTMLElement
    attributes(:html_element => ([:form]))
  end
  class Legend < HTMLElement
    attributes(:string => ([:align]))
  end
  class Label < HTMLElement
    attributes(:html_element => ([:form, :control]), :string => ([:html_for]))
  end
  class Input < HTMLElement
    attributes(:string => ([:accept, :alt, :autocomplete, :form_action, :form_enctype, :form_method, :form_target, :height, :max, :min, :name, :pattern, :placeholder, :src, :step, :type, :default_value, :value, :width, :validity, :validation_message]), :bool => ([:autofocus, :default_checked, :checked, :disabled, :form_no_validate, :indeterminate, :multiple, :read_only, :required, :will_validate]), :html_element => ([:form, :list, :selected_option]), :list => ([:files, :labels]), :int => ([:max_length, :size, :selection_start, :selection_end]), :date => ([:value_as_date]), :float => ([:value_as_number]))
  end
  class Input < HTMLElement
    attributes(:string => ([:align, :use_map]))
  end
  class Button < HTMLElement
    attributes(:bool => ([:autofocus, :disabled, :will_validate]), :html_element => ([:form]), :string => ([:form_action, :form_enctype, :form_method, :form_no_validate, :form_target, :name, :type, :value, :validity, :validation_message]), :list => ([:labels]))
  end
  class Select < HTMLElement
    attributes(:bool => ([:autofocus, :disabled, :multiple, :will_validate]), :html_element => ([:form]), :string => ([:name, :type, :value, :validity, :validation_message]), :int => ([:size, :length, :selected_index]), :html_collection => ([:options, :selected_options]), :list => ([:labels]))
  end
  class DataList < HTMLElement
    attributes(:html_collection => ([:options]))
  end
  class OptGroup < HTMLElement
    attributes(:bool => ([:disabled]), :string => ([:label]))
  end
  class Option < HTMLElement
    attributes(:bool => ([:disabled, :default_selected, :selected]), :html_element => ([:form]), :string => ([:label, :value, :text]), :int => ([:index]))
  end
  class TextArea < HTMLElement
    attributes(:bool => ([:autofocus, :disabled, :read_only, :required, :will_validate]), :int => ([:cols, :max_length, :rows, :text_length, :selection_start, :selection_end]), :html_element => ([:form]), :string => ([:name, :placeholder, :wrap, :type, :default_value, :value, :validity, :validation_message]), :list => ([:labels]))
  end
  class Keygen < HTMLElement
    attributes(:bool => ([:autofocus, :disabled, :will_validate]), :string => ([:challenge, :keytype, :name, :type, :validity, :validation_message]), :html_element => ([:form]), :list => ([:labels]))
  end
  class Output < HTMLElement
    attributes(:token_list => ([:html_for]), :html_element => ([:form]), :string => ([:name, :type, :default_value, :value, :validity, :validation_message]), :bool => ([:will_validate]), :list => ([:labels]))
  end
  class Progress < HTMLElement
    attributes(:float => ([:value, :max, :position]), :html_element => ([:form]), :list => ([:labels]))
  end
  class Meter < HTMLElement
    attributes(:float => ([:value, :min, :max, :low, :high, :optimum]), :html_element => ([:form]), :list => ([:labels]))
  end

  class Details < HTMLElement
    attributes(:bool => ([:open]))
  end
  class Command < HTMLElement
    attributes(:string => ([:type, :label, :icon, :radiogroup]), :bool => ([:disabled, :checked]))
  end
  class Menu < HTMLElement
    attributes(:string => ([:type, :label]))
  end
  class Menu < HTMLElement
    attributes(:bool => ([:compact]))
  end
  class Device < HTMLElement
    attributes(:string => ([:type, :data]))
  end




























  class Applet < HTMLElement
    attributes(:string => ([:align, :alt, :archive, :code, :code_base, :height, :name, :object, :width]), :int => ([:hspace, :vspace]))
  end
  class Marquee < HTMLElement
    attributes(:string => ([:behavior, :bg_color, :direction, :height, :true_speed, :width]), :int => ([:hspace, :loop, :scroll_amount, :scroll_delay, :vspace]), :function => ([:onbounce, :onfinish, :onstart]))
  end
  class FrameSet < HTMLElement
    attributes(:string => ([:cols, :rows]), :function => ([:onafterprint, :onbeforeprint, :onbeforeunload, :onblur, :onerror, :onfocus, :onhashchange, :onload, :onmessage, :onoffline, :ononline, :onpagehide, :onpageshow, :onpopstate, :onredo, :onresize, :onstorage, :onundo, :onunload]))
  end
  class Frame < HTMLElement
    attributes(:string => ([:frame_border, :long_desc, :margin_height, :margin_width, :name, :scrolling, :src]), :bool => ([:no_resize]), :document => ([:content_document]))
  end
  class BaseFont < HTMLElement
    attributes(:string => ([:color, :face]), :int => ([:size]))
  end
  class Directory < HTMLElement
    attributes(:bool => ([:compact]))
  end
  class Font < HTMLElement
    attributes(:string => ([:color, :face, :size]))
  end
  class AnchorCollection < ElementCollection
    def element_class; Anchor; end
  end

  class HTMLElementCollection < ElementCollection
    def element_class; HTMLElement; end
  end

  class AreaCollection < ElementCollection
    def element_class; Area; end
  end

  class AudioCollection < ElementCollection
    def element_class; Audio; end
  end

  class BaseCollection < ElementCollection
    def element_class; Base; end
  end

  class QuoteCollection < ElementCollection
    def element_class; Quote; end
  end

  class BodyCollection < ElementCollection
    def element_class; Body; end
  end

  class BRCollection < ElementCollection
    def element_class; BR; end
  end

  class ButtonCollection < ElementCollection
    def element_class; Button; end
  end

  class CanvasCollection < ElementCollection
    def element_class; Canvas; end
  end

  class TableCaptionCollection < ElementCollection
    def element_class; TableCaption; end
  end

  class TableColCollection < ElementCollection
    def element_class; TableCol; end
  end

  class CommandCollection < ElementCollection
    def element_class; Command; end
  end

  class DataListCollection < ElementCollection
    def element_class; DataList; end
  end

  class ModCollection < ElementCollection
    def element_class; Mod; end
  end

  class DetailsCollection < ElementCollection
    def element_class; Details; end
  end

  class DivCollection < ElementCollection
    def element_class; Div; end
  end

  class DListCollection < ElementCollection
    def element_class; DList; end
  end

  class EmbedCollection < ElementCollection
    def element_class; Embed; end
  end

  class FieldSetCollection < ElementCollection
    def element_class; FieldSet; end
  end

  class FormCollection < ElementCollection
    def element_class; Form; end
  end

  class HeadingCollection < ElementCollection
    def element_class; Heading; end
  end

  class HeadCollection < ElementCollection
    def element_class; Head; end
  end

  class HRCollection < ElementCollection
    def element_class; HR; end
  end

  class HtmlCollection < ElementCollection
    def element_class; Html; end
  end

  class IFrameCollection < ElementCollection
    def element_class; IFrame; end
  end

  class ImageCollection < ElementCollection
    def element_class; Image; end
  end

  class InputCollection < ElementCollection
    def element_class; Input; end
  end

  class KeygenCollection < ElementCollection
    def element_class; Keygen; end
  end

  class LabelCollection < ElementCollection
    def element_class; Label; end
  end

  class LegendCollection < ElementCollection
    def element_class; Legend; end
  end

  class LICollection < ElementCollection
    def element_class; LI; end
  end

  class MapCollection < ElementCollection
    def element_class; Map; end
  end

  class MenuCollection < ElementCollection
    def element_class; Menu; end
  end

  class MetaCollection < ElementCollection
    def element_class; Meta; end
  end

  class MeterCollection < ElementCollection
    def element_class; Meter; end
  end

  class ObjectCollection < ElementCollection
    def element_class; Object; end
  end

  class OListCollection < ElementCollection
    def element_class; OList; end
  end

  class OptGroupCollection < ElementCollection
    def element_class; OptGroup; end
  end

  class OptionCollection < ElementCollection
    def element_class; Option; end
  end

  class OutputCollection < ElementCollection
    def element_class; Output; end
  end

  class ParagraphCollection < ElementCollection
    def element_class; Paragraph; end
  end

  class ParamCollection < ElementCollection
    def element_class; Param; end
  end

  class PreCollection < ElementCollection
    def element_class; Pre; end
  end

  class ProgressCollection < ElementCollection
    def element_class; Progress; end
  end

  class ScriptCollection < ElementCollection
    def element_class; Script; end
  end

  class SelectCollection < ElementCollection
    def element_class; Select; end
  end

  class SourceCollection < ElementCollection
    def element_class; Source; end
  end

  class SpanCollection < ElementCollection
    def element_class; Span; end
  end

  class StyleCollection < ElementCollection
    def element_class; Style; end
  end

  class TableCollection < ElementCollection
    def element_class; Table; end
  end

  class TableSectionCollection < ElementCollection
    def element_class; TableSection; end
  end

  class TableDataCellCollection < ElementCollection
    def element_class; TableDataCell; end
  end

  class TextAreaCollection < ElementCollection
    def element_class; TextArea; end
  end

  class TableHeaderCellCollection < ElementCollection
    def element_class; TableHeaderCell; end
  end

  class TimeCollection < ElementCollection
    def element_class; Time; end
  end

  class TitleCollection < ElementCollection
    def element_class; Title; end
  end

  class TableRowCollection < ElementCollection
    def element_class; TableRow; end
  end

  class TrackCollection < ElementCollection
    def element_class; Track; end
  end

  class UListCollection < ElementCollection
    def element_class; UList; end
  end

  class VideoCollection < ElementCollection
    def element_class; Video; end
  end

  module Container
    Watir.tag_to_class[:a] = Anchor

    #
    # @return [Anchor]
    #

    def a(*args)
      Anchor.new(self, {:tag_name => "a"}, *args)
    end

    #
    # @return [AnchorCollection]
    #

    def as(*args)
      AnchorCollection.new(self, {:tag_name => "a"}, *args)
    end

    Watir.tag_to_class[:abbr] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def abbr(*args)
      HTMLElement.new(self, {:tag_name => "abbr"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def abbrs(*args)
      HTMLElementCollection.new(self, {:tag_name => "abbr"}, *args)
    end

    Watir.tag_to_class[:address] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def address(*args)
      HTMLElement.new(self, {:tag_name => "address"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def addresses(*args)
      HTMLElementCollection.new(self, {:tag_name => "address"}, *args)
    end

    Watir.tag_to_class[:area] = Area

    #
    # @return [Area]
    #

    def area(*args)
      Area.new(self, {:tag_name => "area"}, *args)
    end

    #
    # @return [AreaCollection]
    #

    def areas(*args)
      AreaCollection.new(self, {:tag_name => "area"}, *args)
    end

    Watir.tag_to_class[:article] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def article(*args)
      HTMLElement.new(self, {:tag_name => "article"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def articles(*args)
      HTMLElementCollection.new(self, {:tag_name => "article"}, *args)
    end

    Watir.tag_to_class[:aside] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def aside(*args)
      HTMLElement.new(self, {:tag_name => "aside"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def asides(*args)
      HTMLElementCollection.new(self, {:tag_name => "aside"}, *args)
    end

    Watir.tag_to_class[:audio] = Audio

    #
    # @return [Audio]
    #

    def audio(*args)
      Audio.new(self, {:tag_name => "audio"}, *args)
    end

    #
    # @return [AudioCollection]
    #

    def audios(*args)
      AudioCollection.new(self, {:tag_name => "audio"}, *args)
    end

    Watir.tag_to_class[:b] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def b(*args)
      HTMLElement.new(self, {:tag_name => "b"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def bs(*args)
      HTMLElementCollection.new(self, {:tag_name => "b"}, *args)
    end

    Watir.tag_to_class[:base] = Base

    #
    # @return [Base]
    #

    def base(*args)
      Base.new(self, {:tag_name => "base"}, *args)
    end

    #
    # @return [BaseCollection]
    #

    def bases(*args)
      BaseCollection.new(self, {:tag_name => "base"}, *args)
    end

    Watir.tag_to_class[:bdo] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def bdo(*args)
      HTMLElement.new(self, {:tag_name => "bdo"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def bdos(*args)
      HTMLElementCollection.new(self, {:tag_name => "bdo"}, *args)
    end

    Watir.tag_to_class[:blockquote] = Quote

    #
    # @return [Quote]
    #

    def blockquote(*args)
      Quote.new(self, {:tag_name => "blockquote"}, *args)
    end

    #
    # @return [QuoteCollection]
    #

    def blockquotes(*args)
      QuoteCollection.new(self, {:tag_name => "blockquote"}, *args)
    end

    Watir.tag_to_class[:body] = Body

    #
    # @return [Body]
    #

    def body(*args)
      Body.new(self, {:tag_name => "body"}, *args)
    end

    #
    # @return [BodyCollection]
    #

    def bodys(*args)
      BodyCollection.new(self, {:tag_name => "body"}, *args)
    end

    Watir.tag_to_class[:br] = BR

    #
    # @return [BR]
    #

    def br(*args)
      BR.new(self, {:tag_name => "br"}, *args)
    end

    #
    # @return [BRCollection]
    #

    def brs(*args)
      BRCollection.new(self, {:tag_name => "br"}, *args)
    end

    Watir.tag_to_class[:button] = Button

    #
    # @return [Button]
    #

    def button(*args)
      Button.new(self, {:tag_name => "button"}, *args)
    end

    #
    # @return [ButtonCollection]
    #

    def buttons(*args)
      ButtonCollection.new(self, {:tag_name => "button"}, *args)
    end

    Watir.tag_to_class[:canvas] = Canvas

    #
    # @return [Canvas]
    #

    def canvas(*args)
      Canvas.new(self, {:tag_name => "canvas"}, *args)
    end

    #
    # @return [CanvasCollection]
    #

    def canvases(*args)
      CanvasCollection.new(self, {:tag_name => "canvas"}, *args)
    end

    Watir.tag_to_class[:caption] = TableCaption

    #
    # @return [TableCaption]
    #

    def caption(*args)
      TableCaption.new(self, {:tag_name => "caption"}, *args)
    end

    #
    # @return [TableCaptionCollection]
    #

    def captions(*args)
      TableCaptionCollection.new(self, {:tag_name => "caption"}, *args)
    end

    Watir.tag_to_class[:cite] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def cite(*args)
      HTMLElement.new(self, {:tag_name => "cite"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def cites(*args)
      HTMLElementCollection.new(self, {:tag_name => "cite"}, *args)
    end

    Watir.tag_to_class[:code] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def code(*args)
      HTMLElement.new(self, {:tag_name => "code"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def codes(*args)
      HTMLElementCollection.new(self, {:tag_name => "code"}, *args)
    end

    Watir.tag_to_class[:col] = TableCol

    #
    # @return [TableCol]
    #

    def col(*args)
      TableCol.new(self, {:tag_name => "col"}, *args)
    end

    #
    # @return [TableColCollection]
    #

    def cols(*args)
      TableColCollection.new(self, {:tag_name => "col"}, *args)
    end

    Watir.tag_to_class[:colgroup] = TableCol

    #
    # @return [TableCol]
    #

    def colgroup(*args)
      TableCol.new(self, {:tag_name => "colgroup"}, *args)
    end

    #
    # @return [TableColCollection]
    #

    def colgroups(*args)
      TableColCollection.new(self, {:tag_name => "colgroup"}, *args)
    end

    Watir.tag_to_class[:command] = Command

    #
    # @return [Command]
    #

    def command(*args)
      Command.new(self, {:tag_name => "command"}, *args)
    end

    #
    # @return [CommandCollection]
    #

    def commands(*args)
      CommandCollection.new(self, {:tag_name => "command"}, *args)
    end

    Watir.tag_to_class[:datalist] = DataList

    #
    # @return [DataList]
    #

    def datalist(*args)
      DataList.new(self, {:tag_name => "datalist"}, *args)
    end

    #
    # @return [DataListCollection]
    #

    def datalists(*args)
      DataListCollection.new(self, {:tag_name => "datalist"}, *args)
    end

    Watir.tag_to_class[:dd] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def dd(*args)
      HTMLElement.new(self, {:tag_name => "dd"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def dds(*args)
      HTMLElementCollection.new(self, {:tag_name => "dd"}, *args)
    end

    Watir.tag_to_class[:del] = Mod

    #
    # @return [Mod]
    #

    def del(*args)
      Mod.new(self, {:tag_name => "del"}, *args)
    end

    #
    # @return [ModCollection]
    #

    def dels(*args)
      ModCollection.new(self, {:tag_name => "del"}, *args)
    end

    Watir.tag_to_class[:details] = Details

    #
    # @return [Details]
    #

    def details(*args)
      Details.new(self, {:tag_name => "details"}, *args)
    end

    #
    # @return [DetailsCollection]
    #

    def details(*args)
      DetailsCollection.new(self, {:tag_name => "details"}, *args)
    end

    Watir.tag_to_class[:dfn] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def dfn(*args)
      HTMLElement.new(self, {:tag_name => "dfn"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def dfns(*args)
      HTMLElementCollection.new(self, {:tag_name => "dfn"}, *args)
    end

    Watir.tag_to_class[:div] = Div

    #
    # @return [Div]
    #

    def div(*args)
      Div.new(self, {:tag_name => "div"}, *args)
    end

    #
    # @return [DivCollection]
    #

    def divs(*args)
      DivCollection.new(self, {:tag_name => "div"}, *args)
    end

    Watir.tag_to_class[:dl] = DList

    #
    # @return [DList]
    #

    def dl(*args)
      DList.new(self, {:tag_name => "dl"}, *args)
    end

    #
    # @return [DListCollection]
    #

    def dls(*args)
      DListCollection.new(self, {:tag_name => "dl"}, *args)
    end

    Watir.tag_to_class[:dt] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def dt(*args)
      HTMLElement.new(self, {:tag_name => "dt"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def dts(*args)
      HTMLElementCollection.new(self, {:tag_name => "dt"}, *args)
    end

    Watir.tag_to_class[:em] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def em(*args)
      HTMLElement.new(self, {:tag_name => "em"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def ems(*args)
      HTMLElementCollection.new(self, {:tag_name => "em"}, *args)
    end

    Watir.tag_to_class[:embed] = Embed

    #
    # @return [Embed]
    #

    def embed(*args)
      Embed.new(self, {:tag_name => "embed"}, *args)
    end

    #
    # @return [EmbedCollection]
    #

    def embeds(*args)
      EmbedCollection.new(self, {:tag_name => "embed"}, *args)
    end

    Watir.tag_to_class[:fieldset] = FieldSet

    #
    # @return [FieldSet]
    #

    def fieldset(*args)
      FieldSet.new(self, {:tag_name => "fieldset"}, *args)
    end

    #
    # @return [FieldSetCollection]
    #

    def fieldsets(*args)
      FieldSetCollection.new(self, {:tag_name => "fieldset"}, *args)
    end

    Watir.tag_to_class[:figcaption] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def figcaption(*args)
      HTMLElement.new(self, {:tag_name => "figcaption"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def figcaptions(*args)
      HTMLElementCollection.new(self, {:tag_name => "figcaption"}, *args)
    end

    Watir.tag_to_class[:figure] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def figure(*args)
      HTMLElement.new(self, {:tag_name => "figure"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def figures(*args)
      HTMLElementCollection.new(self, {:tag_name => "figure"}, *args)
    end

    Watir.tag_to_class[:footer] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def footer(*args)
      HTMLElement.new(self, {:tag_name => "footer"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def footers(*args)
      HTMLElementCollection.new(self, {:tag_name => "footer"}, *args)
    end

    Watir.tag_to_class[:form] = Form

    #
    # @return [Form]
    #

    def form(*args)
      Form.new(self, {:tag_name => "form"}, *args)
    end

    #
    # @return [FormCollection]
    #

    def forms(*args)
      FormCollection.new(self, {:tag_name => "form"}, *args)
    end

    Watir.tag_to_class[:h1] = Heading

    #
    # @return [Heading]
    #

    def h1(*args)
      Heading.new(self, {:tag_name => "h1"}, *args)
    end

    #
    # @return [HeadingCollection]
    #

    def h1s(*args)
      HeadingCollection.new(self, {:tag_name => "h1"}, *args)
    end

    Watir.tag_to_class[:h2] = Heading

    #
    # @return [Heading]
    #

    def h2(*args)
      Heading.new(self, {:tag_name => "h2"}, *args)
    end

    #
    # @return [HeadingCollection]
    #

    def h2s(*args)
      HeadingCollection.new(self, {:tag_name => "h2"}, *args)
    end

    Watir.tag_to_class[:h3] = Heading

    #
    # @return [Heading]
    #

    def h3(*args)
      Heading.new(self, {:tag_name => "h3"}, *args)
    end

    #
    # @return [HeadingCollection]
    #

    def h3s(*args)
      HeadingCollection.new(self, {:tag_name => "h3"}, *args)
    end

    Watir.tag_to_class[:h4] = Heading

    #
    # @return [Heading]
    #

    def h4(*args)
      Heading.new(self, {:tag_name => "h4"}, *args)
    end

    #
    # @return [HeadingCollection]
    #

    def h4s(*args)
      HeadingCollection.new(self, {:tag_name => "h4"}, *args)
    end

    Watir.tag_to_class[:h5] = Heading

    #
    # @return [Heading]
    #

    def h5(*args)
      Heading.new(self, {:tag_name => "h5"}, *args)
    end

    #
    # @return [HeadingCollection]
    #

    def h5s(*args)
      HeadingCollection.new(self, {:tag_name => "h5"}, *args)
    end

    Watir.tag_to_class[:h6] = Heading

    #
    # @return [Heading]
    #

    def h6(*args)
      Heading.new(self, {:tag_name => "h6"}, *args)
    end

    #
    # @return [HeadingCollection]
    #

    def h6s(*args)
      HeadingCollection.new(self, {:tag_name => "h6"}, *args)
    end

    Watir.tag_to_class[:head] = Head

    #
    # @return [Head]
    #

    def head(*args)
      Head.new(self, {:tag_name => "head"}, *args)
    end

    #
    # @return [HeadCollection]
    #

    def heads(*args)
      HeadCollection.new(self, {:tag_name => "head"}, *args)
    end

    Watir.tag_to_class[:header] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def header(*args)
      HTMLElement.new(self, {:tag_name => "header"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def headers(*args)
      HTMLElementCollection.new(self, {:tag_name => "header"}, *args)
    end

    Watir.tag_to_class[:hgroup] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def hgroup(*args)
      HTMLElement.new(self, {:tag_name => "hgroup"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def hgroups(*args)
      HTMLElementCollection.new(self, {:tag_name => "hgroup"}, *args)
    end

    Watir.tag_to_class[:hr] = HR

    #
    # @return [HR]
    #

    def hr(*args)
      HR.new(self, {:tag_name => "hr"}, *args)
    end

    #
    # @return [HRCollection]
    #

    def hrs(*args)
      HRCollection.new(self, {:tag_name => "hr"}, *args)
    end

    Watir.tag_to_class[:html] = Html

    #
    # @return [Html]
    #

    def html(*args)
      Html.new(self, {:tag_name => "html"}, *args)
    end

    #
    # @return [HtmlCollection]
    #

    def htmls(*args)
      HtmlCollection.new(self, {:tag_name => "html"}, *args)
    end

    Watir.tag_to_class[:i] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def i(*args)
      HTMLElement.new(self, {:tag_name => "i"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def is(*args)
      HTMLElementCollection.new(self, {:tag_name => "i"}, *args)
    end

    Watir.tag_to_class[:iframe] = IFrame

    #
    # @return [IFrame]
    #

    def iframe(*args)
      IFrame.new(self, {:tag_name => "iframe"}, *args)
    end

    #
    # @return [IFrameCollection]
    #

    def iframes(*args)
      IFrameCollection.new(self, {:tag_name => "iframe"}, *args)
    end

    Watir.tag_to_class[:img] = Image

    #
    # @return [Image]
    #

    def image(*args)
      Image.new(self, {:tag_name => "img"}, *args)
    end

    #
    # @return [ImageCollection]
    #

    def images(*args)
      ImageCollection.new(self, {:tag_name => "img"}, *args)
    end

    Watir.tag_to_class[:input] = Input

    #
    # @return [Input]
    #

    def input(*args)
      Input.new(self, {:tag_name => "input"}, *args)
    end

    #
    # @return [InputCollection]
    #

    def inputs(*args)
      InputCollection.new(self, {:tag_name => "input"}, *args)
    end

    Watir.tag_to_class[:ins] = Mod

    #
    # @return [Mod]
    #

    def ins(*args)
      Mod.new(self, {:tag_name => "ins"}, *args)
    end

    #
    # @return [ModCollection]
    #

    def inses(*args)
      ModCollection.new(self, {:tag_name => "ins"}, *args)
    end

    Watir.tag_to_class[:kbd] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def kbd(*args)
      HTMLElement.new(self, {:tag_name => "kbd"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def kbds(*args)
      HTMLElementCollection.new(self, {:tag_name => "kbd"}, *args)
    end

    Watir.tag_to_class[:keygen] = Keygen

    #
    # @return [Keygen]
    #

    def keygen(*args)
      Keygen.new(self, {:tag_name => "keygen"}, *args)
    end

    #
    # @return [KeygenCollection]
    #

    def keygens(*args)
      KeygenCollection.new(self, {:tag_name => "keygen"}, *args)
    end

    Watir.tag_to_class[:label] = Label

    #
    # @return [Label]
    #

    def label(*args)
      Label.new(self, {:tag_name => "label"}, *args)
    end

    #
    # @return [LabelCollection]
    #

    def labels(*args)
      LabelCollection.new(self, {:tag_name => "label"}, *args)
    end

    Watir.tag_to_class[:legend] = Legend

    #
    # @return [Legend]
    #

    def legend(*args)
      Legend.new(self, {:tag_name => "legend"}, *args)
    end

    #
    # @return [LegendCollection]
    #

    def legends(*args)
      LegendCollection.new(self, {:tag_name => "legend"}, *args)
    end

    Watir.tag_to_class[:li] = LI

    #
    # @return [LI]
    #

    def li(*args)
      LI.new(self, {:tag_name => "li"}, *args)
    end

    #
    # @return [LICollection]
    #

    def lis(*args)
      LICollection.new(self, {:tag_name => "li"}, *args)
    end

    Watir.tag_to_class[:map] = Map

    #
    # @return [Map]
    #

    def map(*args)
      Map.new(self, {:tag_name => "map"}, *args)
    end

    #
    # @return [MapCollection]
    #

    def maps(*args)
      MapCollection.new(self, {:tag_name => "map"}, *args)
    end

    Watir.tag_to_class[:mark] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def mark(*args)
      HTMLElement.new(self, {:tag_name => "mark"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def marks(*args)
      HTMLElementCollection.new(self, {:tag_name => "mark"}, *args)
    end

    Watir.tag_to_class[:menu] = Menu

    #
    # @return [Menu]
    #

    def menu(*args)
      Menu.new(self, {:tag_name => "menu"}, *args)
    end

    #
    # @return [MenuCollection]
    #

    def menus(*args)
      MenuCollection.new(self, {:tag_name => "menu"}, *args)
    end

    Watir.tag_to_class[:meta] = Meta

    #
    # @return [Meta]
    #

    def meta(*args)
      Meta.new(self, {:tag_name => "meta"}, *args)
    end

    #
    # @return [MetaCollection]
    #

    def metas(*args)
      MetaCollection.new(self, {:tag_name => "meta"}, *args)
    end

    Watir.tag_to_class[:meter] = Meter

    #
    # @return [Meter]
    #

    def meter(*args)
      Meter.new(self, {:tag_name => "meter"}, *args)
    end

    #
    # @return [MeterCollection]
    #

    def meters(*args)
      MeterCollection.new(self, {:tag_name => "meter"}, *args)
    end

    Watir.tag_to_class[:nav] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def nav(*args)
      HTMLElement.new(self, {:tag_name => "nav"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def navs(*args)
      HTMLElementCollection.new(self, {:tag_name => "nav"}, *args)
    end

    Watir.tag_to_class[:noscript] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def noscript(*args)
      HTMLElement.new(self, {:tag_name => "noscript"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def noscripts(*args)
      HTMLElementCollection.new(self, {:tag_name => "noscript"}, *args)
    end

    Watir.tag_to_class[:object] = Object

    #
    # @return [Object]
    #

    def object(*args)
      Object.new(self, {:tag_name => "object"}, *args)
    end

    #
    # @return [ObjectCollection]
    #

    def objects(*args)
      ObjectCollection.new(self, {:tag_name => "object"}, *args)
    end

    Watir.tag_to_class[:ol] = OList

    #
    # @return [OList]
    #

    def ol(*args)
      OList.new(self, {:tag_name => "ol"}, *args)
    end

    #
    # @return [OListCollection]
    #

    def ols(*args)
      OListCollection.new(self, {:tag_name => "ol"}, *args)
    end

    Watir.tag_to_class[:optgroup] = OptGroup

    #
    # @return [OptGroup]
    #

    def optgroup(*args)
      OptGroup.new(self, {:tag_name => "optgroup"}, *args)
    end

    #
    # @return [OptGroupCollection]
    #

    def optgroups(*args)
      OptGroupCollection.new(self, {:tag_name => "optgroup"}, *args)
    end

    Watir.tag_to_class[:option] = Option

    #
    # @return [Option]
    #

    def option(*args)
      Option.new(self, {:tag_name => "option"}, *args)
    end

    #
    # @return [OptionCollection]
    #

    def options(*args)
      OptionCollection.new(self, {:tag_name => "option"}, *args)
    end

    Watir.tag_to_class[:output] = Output

    #
    # @return [Output]
    #

    def output(*args)
      Output.new(self, {:tag_name => "output"}, *args)
    end

    #
    # @return [OutputCollection]
    #

    def outputs(*args)
      OutputCollection.new(self, {:tag_name => "output"}, *args)
    end

    Watir.tag_to_class[:p] = Paragraph

    #
    # @return [Paragraph]
    #

    def p(*args)
      Paragraph.new(self, {:tag_name => "p"}, *args)
    end

    #
    # @return [ParagraphCollection]
    #

    def ps(*args)
      ParagraphCollection.new(self, {:tag_name => "p"}, *args)
    end

    Watir.tag_to_class[:param] = Param

    #
    # @return [Param]
    #

    def param(*args)
      Param.new(self, {:tag_name => "param"}, *args)
    end

    #
    # @return [ParamCollection]
    #

    def params(*args)
      ParamCollection.new(self, {:tag_name => "param"}, *args)
    end

    Watir.tag_to_class[:pre] = Pre

    #
    # @return [Pre]
    #

    def pre(*args)
      Pre.new(self, {:tag_name => "pre"}, *args)
    end

    #
    # @return [PreCollection]
    #

    def pres(*args)
      PreCollection.new(self, {:tag_name => "pre"}, *args)
    end

    Watir.tag_to_class[:progress] = Progress

    #
    # @return [Progress]
    #

    def progress(*args)
      Progress.new(self, {:tag_name => "progress"}, *args)
    end

    #
    # @return [ProgressCollection]
    #

    def progresses(*args)
      ProgressCollection.new(self, {:tag_name => "progress"}, *args)
    end

    Watir.tag_to_class[:q] = Quote

    #
    # @return [Quote]
    #

    def q(*args)
      Quote.new(self, {:tag_name => "q"}, *args)
    end

    #
    # @return [QuoteCollection]
    #

    def qs(*args)
      QuoteCollection.new(self, {:tag_name => "q"}, *args)
    end

    Watir.tag_to_class[:rp] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def rp(*args)
      HTMLElement.new(self, {:tag_name => "rp"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def rps(*args)
      HTMLElementCollection.new(self, {:tag_name => "rp"}, *args)
    end

    Watir.tag_to_class[:rt] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def rt(*args)
      HTMLElement.new(self, {:tag_name => "rt"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def rts(*args)
      HTMLElementCollection.new(self, {:tag_name => "rt"}, *args)
    end

    Watir.tag_to_class[:ruby] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def ruby(*args)
      HTMLElement.new(self, {:tag_name => "ruby"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def rubies(*args)
      HTMLElementCollection.new(self, {:tag_name => "ruby"}, *args)
    end

    Watir.tag_to_class[:samp] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def samp(*args)
      HTMLElement.new(self, {:tag_name => "samp"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def samps(*args)
      HTMLElementCollection.new(self, {:tag_name => "samp"}, *args)
    end

    Watir.tag_to_class[:script] = Script

    #
    # @return [Script]
    #

    def script(*args)
      Script.new(self, {:tag_name => "script"}, *args)
    end

    #
    # @return [ScriptCollection]
    #

    def scripts(*args)
      ScriptCollection.new(self, {:tag_name => "script"}, *args)
    end

    Watir.tag_to_class[:section] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def section(*args)
      HTMLElement.new(self, {:tag_name => "section"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def sections(*args)
      HTMLElementCollection.new(self, {:tag_name => "section"}, *args)
    end

    Watir.tag_to_class[:select] = Select

    #
    # @return [Select]
    #

    def select(*args)
      Select.new(self, {:tag_name => "select"}, *args)
    end

    #
    # @return [SelectCollection]
    #

    def selects(*args)
      SelectCollection.new(self, {:tag_name => "select"}, *args)
    end

    Watir.tag_to_class[:small] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def small(*args)
      HTMLElement.new(self, {:tag_name => "small"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def smalls(*args)
      HTMLElementCollection.new(self, {:tag_name => "small"}, *args)
    end

    Watir.tag_to_class[:source] = Source

    #
    # @return [Source]
    #

    def source(*args)
      Source.new(self, {:tag_name => "source"}, *args)
    end

    #
    # @return [SourceCollection]
    #

    def sources(*args)
      SourceCollection.new(self, {:tag_name => "source"}, *args)
    end

    Watir.tag_to_class[:span] = Span

    #
    # @return [Span]
    #

    def span(*args)
      Span.new(self, {:tag_name => "span"}, *args)
    end

    #
    # @return [SpanCollection]
    #

    def spans(*args)
      SpanCollection.new(self, {:tag_name => "span"}, *args)
    end

    Watir.tag_to_class[:strong] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def strong(*args)
      HTMLElement.new(self, {:tag_name => "strong"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def strongs(*args)
      HTMLElementCollection.new(self, {:tag_name => "strong"}, *args)
    end

    Watir.tag_to_class[:style] = Style

    #
    # @return [Style]
    #

    def style(*args)
      Style.new(self, {:tag_name => "style"}, *args)
    end

    #
    # @return [StyleCollection]
    #

    def styles(*args)
      StyleCollection.new(self, {:tag_name => "style"}, *args)
    end

    Watir.tag_to_class[:sub] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def sub(*args)
      HTMLElement.new(self, {:tag_name => "sub"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def subs(*args)
      HTMLElementCollection.new(self, {:tag_name => "sub"}, *args)
    end

    Watir.tag_to_class[:summary] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def summary(*args)
      HTMLElement.new(self, {:tag_name => "summary"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def summaries(*args)
      HTMLElementCollection.new(self, {:tag_name => "summary"}, *args)
    end

    Watir.tag_to_class[:sup] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def sup(*args)
      HTMLElement.new(self, {:tag_name => "sup"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def sups(*args)
      HTMLElementCollection.new(self, {:tag_name => "sup"}, *args)
    end

    Watir.tag_to_class[:table] = Table

    #
    # @return [Table]
    #

    def table(*args)
      Table.new(self, {:tag_name => "table"}, *args)
    end

    #
    # @return [TableCollection]
    #

    def tables(*args)
      TableCollection.new(self, {:tag_name => "table"}, *args)
    end

    Watir.tag_to_class[:tbody] = TableSection

    #
    # @return [TableSection]
    #

    def tbody(*args)
      TableSection.new(self, {:tag_name => "tbody"}, *args)
    end

    #
    # @return [TableSectionCollection]
    #

    def tbodys(*args)
      TableSectionCollection.new(self, {:tag_name => "tbody"}, *args)
    end

    Watir.tag_to_class[:td] = TableDataCell

    #
    # @return [TableDataCell]
    #

    def td(*args)
      TableDataCell.new(self, {:tag_name => "td"}, *args)
    end

    #
    # @return [TableDataCellCollection]
    #

    def tds(*args)
      TableDataCellCollection.new(self, {:tag_name => "td"}, *args)
    end

    Watir.tag_to_class[:textarea] = TextArea

    #
    # @return [TextArea]
    #

    def textarea(*args)
      TextArea.new(self, {:tag_name => "textarea"}, *args)
    end

    #
    # @return [TextAreaCollection]
    #

    def textareas(*args)
      TextAreaCollection.new(self, {:tag_name => "textarea"}, *args)
    end

    Watir.tag_to_class[:tfoot] = TableSection

    #
    # @return [TableSection]
    #

    def tfoot(*args)
      TableSection.new(self, {:tag_name => "tfoot"}, *args)
    end

    #
    # @return [TableSectionCollection]
    #

    def tfoots(*args)
      TableSectionCollection.new(self, {:tag_name => "tfoot"}, *args)
    end

    Watir.tag_to_class[:th] = TableHeaderCell

    #
    # @return [TableHeaderCell]
    #

    def th(*args)
      TableHeaderCell.new(self, {:tag_name => "th"}, *args)
    end

    #
    # @return [TableHeaderCellCollection]
    #

    def ths(*args)
      TableHeaderCellCollection.new(self, {:tag_name => "th"}, *args)
    end

    Watir.tag_to_class[:thead] = TableSection

    #
    # @return [TableSection]
    #

    def thead(*args)
      TableSection.new(self, {:tag_name => "thead"}, *args)
    end

    #
    # @return [TableSectionCollection]
    #

    def theads(*args)
      TableSectionCollection.new(self, {:tag_name => "thead"}, *args)
    end

    Watir.tag_to_class[:time] = Time

    #
    # @return [Time]
    #

    def time(*args)
      Time.new(self, {:tag_name => "time"}, *args)
    end

    #
    # @return [TimeCollection]
    #

    def times(*args)
      TimeCollection.new(self, {:tag_name => "time"}, *args)
    end

    Watir.tag_to_class[:title] = Title

    #
    # @return [Title]
    #

    def title(*args)
      Title.new(self, {:tag_name => "title"}, *args)
    end

    #
    # @return [TitleCollection]
    #

    def titles(*args)
      TitleCollection.new(self, {:tag_name => "title"}, *args)
    end

    Watir.tag_to_class[:tr] = TableRow

    #
    # @return [TableRow]
    #

    def tr(*args)
      TableRow.new(self, {:tag_name => "tr"}, *args)
    end

    #
    # @return [TableRowCollection]
    #

    def trs(*args)
      TableRowCollection.new(self, {:tag_name => "tr"}, *args)
    end

    Watir.tag_to_class[:track] = Track

    #
    # @return [Track]
    #

    def track(*args)
      Track.new(self, {:tag_name => "track"}, *args)
    end

    #
    # @return [TrackCollection]
    #

    def tracks(*args)
      TrackCollection.new(self, {:tag_name => "track"}, *args)
    end

    Watir.tag_to_class[:ul] = UList

    #
    # @return [UList]
    #

    def ul(*args)
      UList.new(self, {:tag_name => "ul"}, *args)
    end

    #
    # @return [UListCollection]
    #

    def uls(*args)
      UListCollection.new(self, {:tag_name => "ul"}, *args)
    end

    Watir.tag_to_class[:var] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def var(*args)
      HTMLElement.new(self, {:tag_name => "var"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def vars(*args)
      HTMLElementCollection.new(self, {:tag_name => "var"}, *args)
    end

    Watir.tag_to_class[:video] = Video

    #
    # @return [Video]
    #

    def video(*args)
      Video.new(self, {:tag_name => "video"}, *args)
    end

    #
    # @return [VideoCollection]
    #

    def videos(*args)
      VideoCollection.new(self, {:tag_name => "video"}, *args)
    end

    Watir.tag_to_class[:wbr] = HTMLElement

    #
    # @return [HTMLElement]
    #

    def wbr(*args)
      HTMLElement.new(self, {:tag_name => "wbr"}, *args)
    end

    #
    # @return [HTMLElementCollection]
    #

    def wbrs(*args)
      HTMLElementCollection.new(self, {:tag_name => "wbr"}, *args)
    end

  end # Container
end # Watir
