name: Linux Tests

on:
  - push
  - pull_request

jobs:
  chrome-test:
    name: Chrome Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [ 'chrome' ]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - run: bundle install
      - uses: ./.github/actions/install-chrome
      - run: Xvfb :99 &
      - run: |
          bundle exec rake spec:${{ matrix.task }}
        env:
          DISPLAY: :99

  firefox-test:
    name: Firefox Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [ 'firefox' ]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - run: bundle install
      - run: Xvfb :99 &
      - run: |
          bundle exec rake spec:${{ matrix.task }}
        env:
          DISPLAY: :99

  documentation-test:
    name: Yard Doc Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - run: bundle install
      - uses: ./.github/actions/install-chrome
      - run: Xvfb :99 &
      - run: |
          bundle exec rake yard:doctest
        env:
          DISPLAY: :99
