name: Windows Tests

on:
  - push
  - pull_request

jobs:
  chrome-test:
    name: Chrome Test
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        task: [ 'chrome' ]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - run: bundle install
      - run: |
          bundle exec rake spec:${{ matrix.task }}
  firefox-test:
    name: Firefox Test
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        task: [ 'firefox' ]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - run: bundle install
      - run: |
          bundle exec rake spec:${{ matrix.task }}


